### PR TITLE
Diet Reminder CRUD

### PR DESCRIPTION
**Pull request by k1ycee**
#59

### CODE REVIEW

**Comment by iyiola-dev** [comment]
Resolve conflicts and re send pr

**Comment by Crazelu** [comment]
Resolved the conflict. It's a tiny ish...

**Comment by k1ycee** [comment]
Yeah about that who is messing with our pubspec.lock file

**Comment by Crazelu** [comment]
Literally everyone is.
We need to add it to gitIgnore

**Comment by k1ycee** [comment]
Okay cos that is where my conflict came from

**Pull request merged**
